numpy is a library used for working with arrays

In [4]:
import numpy

In [6]:
print(numpy.__version__)

2.3.3


In [5]:
my_array1 = numpy.array([1, 2, 3, 4, 5])

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/mangoes/.cache/pypoetry/virtualenvs/ml-1VGOpNek-py3.12/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
my_array = np.array([1, 2, 3, 4, 5])    
print(my_array)
print(type(my_array))  # Output: <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


0-D Arrays-arrays that are scalar

In [7]:
my_0_D_array = np.array(42)
print(my_0_D_array)
print(type(my_0_D_array))  # Output: <class 'numpy.ndarray'>

42
<class 'numpy.ndarray'>


1-D Arrays: arrays that are like list actually its a vector

In [8]:
our_array_1D = np.array([1, 2, 3, 4, 5])
print(our_array_1D)
print(type(our_array_1D))  # Output: <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


2-D Arrays-represents a matrix  2nd ,order tensors.

In [9]:
our_2D_array = np.array([[1, 2, 3], [4, 5, 6]])
print(our_2D_array)
print(type(our_2D_array))  # Output: <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


3-D arrays-matrix plus an addition of 1d array

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

checking number of dimensions

In [11]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


NumPy Array Slicing

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [20]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array[4:10:2])  # Elements from index 4 to 9 with a step of 2

[5 7 9]


NumPy Data Types

In [21]:
array=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array.dtype)  # Output: int64

int64


In [25]:
array=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(type(array))  # this gets the type of the array object
print(array.dtype)  # this gets the data type of the elements in the array

<class 'numpy.ndarray'>
int64


In [26]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Converting Data Type on Existing Arrays

change the data type of an existing array, is to make a copy of the array with the astype() method. then you can specify the datatype you want to chaange to

In [29]:
before_array = np.array([1, 2, 3, 4, 5])
changed_array = before_array.astype(np.int32)
print(changed_array)
another_changed_array = before_array.astype('f')
print(f'another_changed_array: {another_changed_array}')

[1 2 3 4 5]
another_changed_array: [1. 2. 3. 4. 5.]


In [32]:
my_array = np.array([1, 2, 3, 4, 5])
my_new_array = my_array.astype(bool)
print(my_new_array)
print(my_new_array.dtype)



[ True  True  True  True  True]
bool


numpy copy vs view

copy:fabricated data from the original(aka view)
view:original data

In [33]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [34]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


copies owns the data, and views does not own the data


In [35]:
#check who owns the data
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()  
# base attribute returns the base object if the array is a view, and None if the array owns its data

print(x.base)  # Output: None, as x is a copy and owns its data
print(y.base)  # Output: Original array, as y is a view and does not

None
[1 2 3 4 5]


shape of an array:the number of elements in each dimension(rows and columns).

In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)
(2, 4)


In [38]:
arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8]], ndmin=3)
print(arr.shape)



(1, 2, 4)


In [39]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)


[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


 Reshape:
 changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
arr=np.array([1,2,3,4,4,5,6,8,9,10,12,17])
new_arr=arr.reshape(4,3) # the new array will have  4 arrays with each 3 elements
print(new_arr)

In [40]:

# Create a 2D array
arr = np.arange(12).reshape(3, 4)
print("Array:\n", arr)
print("Shape:", arr.shape)  # (3, 4) -> 3 rows, 4 columns
print("Strides:", arr.strides) # (32, 8) -> Bytes to next row, bytes to next column
print("Dtype:", arr.dtype)   # int64 (platform dependent)

# A view is a different "look" at the same data
arr_view = arr[::2, ::2] # Every other row and column
print("\nView (arr[::2, ::2]):\n", arr_view)
arr_view[0, 0] = 999
print("Original arr after modifying view:\n", arr) # The original is changed!

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Strides: (32, 8)
Dtype: int64

View (arr[::2, ::2]):
 [[ 0  2]
 [ 8 10]]
Original arr after modifying view:
 [[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


VECTORIZATION

In [45]:
# The SLOW way (using loops - DON'T DO THIS)
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# %timeit is a Jupyter magic command to time execution.
# Let's simulate it conceptually.
slow_result = [a_i + b_i for a_i, b_i in zip(a, b)] # Very Slow!



In [46]:
# The FAST way (vectorized - DO THIS)
fast_result = a + b # Blazingly fast

# Other vectorized operations
print("Element-wise multiplication:", a * b)
print("Exponential:", np.exp(a))
print("Comparison:", a > 0.5)
print("Matrix multiplication (1D is dot product):", np.dot(a, b))

Element-wise multiplication: [0.01685132 0.14545468 0.25636476 ... 0.11139584 0.06712077 0.01572481]
Exponential: [2.31148576 1.66246258 1.64650332 ... 1.50802714 1.29253054 1.51750017]
Comparison: [ True  True False ... False False False]
Matrix multiplication (1D is dot product): 250325.50983980662


Exercise 1: Create two 1D arrays of size 10,000 with random integers. Time the difference between adding them with a list comprehension vs. numpy vectorization. (Use %timeit in Jupyter or time.time() in a script).

In [48]:
import time
# Create two arrays of size 10,000 (integers to match the exercise request)
my__array1 = np.random.randint(0, 100, 10000)
my__array2 = np.random.randint(0, 100, 10000)
# using list comprehension (explicit Python loop)
start = time.time()
my_solution_sum = [my__array1[i] + my__array2[i] for i in range(len(my__array1))]
list_time = time.time() - start
# using numpy vectorization
start = time.time()
my_vectorized_sum = my__array1 + my__array2
vectorized_time = time.time() - start
print(f'list_time: {list_time:.6f}s, vectorized_time: {vectorized_time:.6f}s')
# verify the results are equal
print('Equal results:', np.array_equal(np.array(my_solution_sum), my_vectorized_sum))


list_time: 0.029094s, vectorized_time: 0.007139s
Equal results: True


In [49]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [50]:
# Example 1: Scaling a matrix
matrix = np.ones((3, 4))
vector = np.array([1, 2, 3, 4])

# (3, 4) + (4,) -> (3, 4) + (1, 4) -> (3, 4)
result = matrix + vector
print("Matrix + Vector:\n", result)

# Example 2: More complex broadcasting
A = np.arange(3).reshape(3, 1)   # Shape (3, 1)
B = np.arange(4).reshape(1, 4)   # Shape (1, 4)

# (3, 1) + (1, 4) -> (3, 4)
C = A + B
print("\nOuter sum via broadcasting:\n", C)

Matrix + Vector:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]

Outer sum via broadcasting:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


Broadcasting: Numpy's Superpower

Broadcasting allows operations between arrays of different shapes, without making copies of the data.

Rule: Dimensions are compared from right to left. They are compatible if they are equal, or one of them is 1.

In [ ]:
# Example 1: Scaling a matrix
matrix = np.ones((3, 4))
vector = np.array([1, 2, 3, 4])

# (3, 4) + (4,) -> (3, 4) + (1, 4) -> (3, 4)
result = matrix + vector
print("Matrix + Vector:\n", result)

# Example 2: More complex broadcasting
A = np.arange(3).reshape(3, 1)   # Shape (3, 1)
B = np.arange(4).reshape(1, 4)   # Shape (1, 4)

# (3, 1) + (1, 4) -> (3, 4)
C = A + B
print("\nOuter sum via broadcasting:\n", C)