numpy is a library used for working with arrays

In [6]:
import numpy

In [7]:
print(numpy.__version__)

2.3.3


In [8]:
my_array1 = numpy.array([1, 2, 3, 4, 5])

In [9]:
import numpy as np

In [10]:
np

<module 'numpy' from '/home/mangoes/.cache/pypoetry/virtualenvs/ml-1VGOpNek-py3.12/lib/python3.12/site-packages/numpy/__init__.py'>

In [11]:
my_array = np.array([1, 2, 3, 4, 5])    
print(my_array)
print(type(my_array))  # Output: <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


0-D Arrays-arrays that are scalar

In [12]:
my_0_D_array = np.array(42)
print(my_0_D_array)
print(type(my_0_D_array))  # Output: <class 'numpy.ndarray'>

42
<class 'numpy.ndarray'>


1-D Arrays: arrays that are like list actually its a vector

In [13]:
our_array_1D = np.array([1, 2, 3, 4, 5])
print(our_array_1D)
print(type(our_array_1D))  # Output: <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


2-D Arrays-represents a matrix  2nd ,order tensors.

In [14]:
our_2D_array = np.array([[1, 2, 3], [4, 5, 6]])
print(our_2D_array)
print(type(our_2D_array))  # Output: <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


3-D arrays-matrix plus an addition of 1d array

In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

checking number of dimensions

In [16]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


NumPy Array Slicing

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [20]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array[4:10:2])  # Elements from index 4 to 9 with a step of 2

[5 7 9]


NumPy Data Types

In [21]:
array=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array.dtype)  # Output: int64

int64


In [22]:
array=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(type(array))  # this gets the type of the array object
print(array.dtype)  # this gets the data type of the elements in the array

<class 'numpy.ndarray'>
int64


In [23]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Converting Data Type on Existing Arrays

change the data type of an existing array, is to make a copy of the array with the astype() method. then you can specify the datatype you want to chaange to

In [24]:
before_array = np.array([1, 2, 3, 4, 5])
changed_array = before_array.astype(np.int32)
print(changed_array)
another_changed_array = before_array.astype('f')
print(f'another_changed_array: {another_changed_array}')

[1 2 3 4 5]
another_changed_array: [1. 2. 3. 4. 5.]


In [25]:
my_array = np.array([1, 2, 3, 4, 5])
my_new_array = my_array.astype(bool)
print(my_new_array)
print(my_new_array.dtype)



[ True  True  True  True  True]
bool


numpy copy vs view

copy:fabricated data from the original(aka view)
view:original data

In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


copies owns the data, and views does not own the data


In [28]:
#check who owns the data
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()  
# base attribute returns the base object if the array is a view, and None if the array owns its data

print(x.base)  # Output: None, as x is a copy and owns its data
print(y.base)  # Output: Original array, as y is a view and does not

None
[1 2 3 4 5]


shape of an array:the number of elements in each dimension(rows and columns).

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)
(2, 4)


In [30]:
arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8]], ndmin=3)
print(arr.shape)



(1, 2, 4)


In [31]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)


[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


 Reshape:
 changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [32]:
arr=np.array([1,2,3,4,4,5,6,8,9,10,12,17])
new_arr=arr.reshape(4,3) # the new array will have  4 arrays with each 3 elements
print(new_arr)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  8  9]
 [10 12 17]]


In [33]:

# Create a 2D array
arr = np.arange(12).reshape(3, 4)
print("Array:\n", arr)
print("Shape:", arr.shape)  # (3, 4) -> 3 rows, 4 columns
print("Strides:", arr.strides) # (32, 8) -> Bytes to next row, bytes to next column
print("Dtype:", arr.dtype)   # int64 (platform dependent)

# A view is a different "look" at the same data
arr_view = arr[::2, ::2] # Every other row and column
print("\nView (arr[::2, ::2]):\n", arr_view)
arr_view[0, 0] = 999
print("Original arr after modifying view:\n", arr) # The original is changed!

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Strides: (32, 8)
Dtype: int64

View (arr[::2, ::2]):
 [[ 0  2]
 [ 8 10]]
Original arr after modifying view:
 [[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


VECTORIZATION

In [34]:
# The SLOW way (using loops - DON'T DO THIS)
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# %timeit is a Jupyter magic command to time execution.
# Let's simulate it conceptually.
slow_result = [a_i + b_i for a_i, b_i in zip(a, b)] # Very Slow!



In [35]:
# The FAST way (vectorized - DO THIS)
fast_result = a + b # Blazingly fast

# Other vectorized operations
print("Element-wise multiplication:", a * b)
print("Exponential:", np.exp(a))
print("Comparison:", a > 0.5)
print("Matrix multiplication (1D is dot product):", np.dot(a, b))

Element-wise multiplication: [0.48670411 0.17560501 0.17372513 ... 0.23671128 0.15228452 0.06583559]
Exponential: [1.82969027 1.2275113  1.79052819 ... 2.08147023 1.48471049 2.19925271]
Comparison: [ True False  True ...  True False  True]
Matrix multiplication (1D is dot product): 250318.8094491379


Exercise 1: Create two 1D arrays of size 10,000 with random integers. Time the difference between adding them with a list comprehension vs. numpy vectorization. (Use %timeit in Jupyter or time.time() in a script).

In [36]:
import time
# Create two arrays of size 10,000 (integers to match the exercise request)
my__array1 = np.random.randint(0, 100, 10000)
my__array2 = np.random.randint(0, 100, 10000)
# using list comprehension (explicit Python loop)
start = time.time()
my_solution_sum = [my__array1[i] + my__array2[i] for i in range(len(my__array1))]
list_time = time.time() - start
# using numpy vectorization
start = time.time()
my_vectorized_sum = my__array1 + my__array2
vectorized_time = time.time() - start
print(f'list_time: {list_time:.6f}s, vectorized_time: {vectorized_time:.6f}s')
# verify the results are equal
print('Equal results:', np.array_equal(np.array(my_solution_sum), my_vectorized_sum))


list_time: 0.011176s, vectorized_time: 0.000103s
Equal results: True


In [37]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [38]:
# Example 1: Scaling a matrix
matrix = np.ones((3, 4))
vector = np.array([1, 2, 3, 4])

# (3, 4) + (4,) -> (3, 4) + (1, 4) -> (3, 4)
result = matrix + vector
print("Matrix + Vector:\n", result)

# Example 2: More complex broadcasting
A = np.arange(3).reshape(3, 1)   # Shape (3, 1)
B = np.arange(4).reshape(1, 4)   # Shape (1, 4)

# (3, 1) + (1, 4) -> (3, 4)
C = A + B
print("\nOuter sum via broadcasting:\n", C)

Matrix + Vector:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]

Outer sum via broadcasting:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


Broadcasting: Numpy's Superpower

Broadcasting allows operations between arrays of different shapes, without making copies of the data.

Rule: Dimensions are compared from right to left. They are compatible if they are equal, or one of them is 1.

In [ ]:
# Example 1: Scaling a matrix
matrix = np.ones((3, 4)) # this creates a 3x4 matrix of ones
vector = np.array([1, 2, 3, 4])

# (3, 4) + (4,) -> (3, 4) + (1, 4) -> (3, 4)
result = matrix + vector
print("Matrix + Vector:\n", result) # result is a 3x4 matrix where each row is [2, 3, 4, 5] after adding the vector to each row

# Example 2: More complex broadcasting
A = np.arange(3).reshape(3, 1)   # Shape (3, 1)
B = np.arange(4).reshape(1, 4)   # Shape (1, 4)

# (3, 1) + (1, 4) -> (3, 4)
C = A + B
print("\nOuter sum via broadcasting:\n", C)

Matrix + Vector:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]

Outer sum via broadcasting:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


By default, np.ones() creates an array of float64 values, so each element is 1.0, not 1.
When NumPy adds a float array and an int array, it upcasts the result to float — to preserve precision.

So the result array has floating-point values:

Exercise 2: Normalize a 10x10 random matrix by subtracting the mean of each row and then dividing by the standard deviation of each row. Do this using broadcasting, without using loops.

In [43]:
import numpy as np

# 1️⃣ Create a 10x10 random matrix (values in [0, 1))
myrandom_array = np.random.rand(10, 10)

# 2️⃣ Compute mean and std for each row
row_mean = myrandom_array.mean(axis=1, keepdims=True)   # shape (10, 1)
row_std = myrandom_array.std(axis=1, keepdims=True)     # shape (10, 1)

# 3️⃣ Normalize each row using broadcasting
normalized_array = (myrandom_array - row_mean) / row_std

# 4️⃣ Verify results
print("Row means after normalization:\n", normalized_array.mean(axis=1))
print("Row stds after normalization:\n", normalized_array.std(axis=1))


Row means after normalization:
 [-3.99680289e-16 -1.33226763e-16 -2.22044605e-16 -1.88737914e-16
  0.00000000e+00  2.22044605e-17  1.11022302e-16  1.27675648e-16
  1.55431223e-16 -9.99200722e-17]
Row stds after normalization:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


axis=1 means “compute across columns”, i.e., per row.

keepdims=True preserves the (10,1) shape, allowing broadcasting to work automatically.

INDEXING

In [44]:
arr = np.arange(25).reshape(5, 5)

# Boolean Indexing: Using a condition to select data
print("Elements greater than 10:", arr[arr > 10])
print("Rows where first element is even:", arr[arr[:, 0] % 2 == 0])

# Fancy Indexing: Using an array of indices
rows = [0, 2, 4]
cols = [1, 3, 0]
print("Elements at (0,1), (2,3), (4,0):", arr[rows, cols])

# Combined: Assign values with conditions
arr[arr % 3 == 0] = -1 # Set all multiples of 3 to -1
print("\nArray after conditional assignment:\n", arr)

Elements greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Rows where first element is even: [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
Elements at (0,1), (2,3), (4,0): [ 1 13 20]

Array after conditional assignment:
 [[-1  1  2 -1  4]
 [ 5 -1  7  8 -1]
 [10 11 -1 13 14]
 [-1 16 17 -1 19]
 [20 -1 22 23 -1]]


Exercise 3: Given an array of 100 random numbers between 0 and 1, replace all values in the first and third quartile (i.e., < 0.25 and > 0.75) with np.nan.

In [46]:

# 1️⃣ Create an array of 100 random numbers in [0, 1)
arr = np.random.rand(100)

# 2️⃣ Replace values in the first (<0.25) and third (>0.75) quartiles with NaN
arr[(arr < 0.25) | (arr > 0.75)] = np.nan # identifies elements below 0.25 or above 0.75.
# 3️⃣ Print results
print(arr)


[0.29105547        nan        nan 0.61597668 0.37518701        nan
        nan 0.33621499 0.61829777        nan 0.68238759 0.58159366
        nan 0.27829091 0.6644813         nan 0.60555157 0.71684129
 0.64716694        nan        nan 0.44468315 0.72195832        nan
        nan        nan 0.55519772 0.56782618        nan        nan
 0.2861983  0.74901693 0.52666655        nan        nan 0.44493965
 0.38610988 0.27425876        nan 0.52312295        nan        nan
 0.32184802 0.46169717        nan 0.4263748  0.56198608 0.73283825
 0.44417746        nan        nan        nan        nan 0.59034481
        nan 0.28065729        nan        nan 0.57261307        nan
 0.56663026        nan 0.52016789 0.45815911        nan 0.62731664
 0.65501987 0.67513005 0.58988992 0.61794028        nan 0.58092057
 0.27184649        nan 0.30249219 0.50719814        nan        nan
 0.53272453 0.54901197 0.28029615 0.29332593 0.52673744 0.59030805
        nan        nan        nan 0.55657213        nan       

Structured Arrays & Record Arrays
For handling heterogeneous data (like a spreadsheet).

In [48]:
# Define a datatype
data_type = np.dtype([('name', 'U10'), ('age', 'i4'), ('height', 'f8')])

# Create a structured array
people = np.array([('Alice', 25, 5.5), ('Bob', 32, 5.9)], dtype=data_type)
print("Structured Array:\n", people)
print("Names:", people['name'])
print("Average age:", np.mean(people['age']))

# Record arrays allow attribute-style access
people_rec = people.view(np.recarray)
print("Names (attribute access):", people_rec.name)

Structured Array:
 [('Alice', 25, 5.5) ('Bob', 32, 5.9)]
Names: ['Alice' 'Bob']
Average age: 28.5
Names (attribute access): ['Alice' 'Bob']


 Efficient Memory Layout: np.ascontiguousarray

CPU access patterns matter. Contiguous arrays are faster.

In [49]:
arr = np.arange(12).reshape(3, 4)
print("Is C-contiguous (row-major)?", arr.flags['C_CONTIGUOUS'])
print("Is F-contiguous (column-major)?", arr.flags['F_CONTIGUOUS'])

# Transpose is a view, and often changes contiguity
arr_t = arr.T
print("\nTranspose is C-contiguous?", arr_t.flags['C_CONTIGUOUS']) # False

# Force contiguity for performance-critical sections
arr_contiguous = np.ascontiguousarray(arr_t)
print("Forced contiguous is C-contiguous?", arr_contiguous.flags['C_CONTIGUOUS']) # True

Is C-contiguous (row-major)? True
Is F-contiguous (column-major)? False

Transpose is C-contiguous? False
Forced contiguous is C-contiguous? True


Universal Functions (ufunc): Create Your Own Vectorized Operations

In [50]:
# A simple element-wise function
def my_slow_function(x):
    return x**2 + np.sin(x)

# Vectorize it!
my_fast_ufunc = np.vectorize(my_slow_function, otypes=[np.float64])

# Test it
data = np.linspace(0, 10, 5)
print("Vectorized function result:", my_fast_ufunc(data))

# For true performance, write it using existing ufuncs:
def my_fast_function(x):
    return x**2 + np.sin(x) # This is already vectorized if x is an array!

print("Optimal function result:", my_fast_function(data))

Vectorized function result: [ 0.          6.84847214 24.04107573 57.18799998 99.45597889]
Optimal function result: [ 0.          6.84847214 24.04107573 57.18799998 99.45597889]


Performance Tuning:
Use np.einsum: For complex tensor operations, it's often the fastest and most readable way.

In [51]:
A = np.random.rand(3, 4)
B = np.random.rand(4, 5)
# Matrix multiplication with einsum
C = np.einsum('ij,jk->ik', A, B)

when to use out= parameter: Avoids creating temporary arrays.

In [54]:
result = np.zeros((1000, 1000))
np.multiply(A, B, out=result) # Puts result directly into pre-allocated array

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) (1000,1000) 